### ISSUE TITLE
About  'use_code_space'

### ISSUE THREAD

**Issue by pennywei** [KlugerLab/SpectralNet#12]
If I  rewrite  {'use_code_space'：False}  in mnist_param .Then error came out.
Here is what I am getting on mnist:
![image](https://user-images.githubusercontent.com/37761988/44952280-90b31c80-aeae-11e8-92f4-12cd2eef3fb9.png)
![image](https://user-images.githubusercontent.com/37761988/44952285-9ad51b00-aeae-11e8-88af-a934efbd3ec5.png)

**Comment by lihenryhfl** [comment]
Hi, thanks for pointing this out. The MNIST dataarray was not being flattened, but now it is!
