### ISSUE TITLE
About ‘ Orthonorm’

### ISSUE THREAD

**Issue by pennywei** [KlugerLab/SpectralNet#13]
Thank you for flattening  MNIST dataarray to solving the problem.
But now the new error came out.(Still unused code space)
Here is what I am getting on mnist:
![2018-09-25 15-37-22](https://user-images.githubusercontent.com/37761988/46002225-10b05900-c0e0-11e8-82b2-416f0013e5ab.png)

**Comment by lihenryhfl** [comment]
It was a small data vector reshaping error. I believe I fixed it. Can you take a look?
