### ISSUE TITLE
Pre-trained weights for new data

### ISSUE THREAD

**Issue by alenamois** [KlugerLab/SpectralNet#15]
Hi, could you please help me? 
I would like to apply your system on my data, however according to the function embed_data(x, dset) I require pre-trained weights. Is it an essential step in the code? If yes, how could I get the weights?

Many thanks in advance for your answer!

**Comment by lihenryhfl** [comment]
Hi, have you tried setting 'use_code_space' in run.py to False? That should tell the model that there aren't any embedding weights to use.

**Comment by alenamois** [comment]
Hi! Many thanks for your answer and for the tip! I will try it out!
