### ISSUE TITLE
What‘s the meaning of the variable "pairs_per_pt" in line 150 of pairs.py?

### ISSUE THREAD

**Issue by gongshuai0606** [KlugerLab/SpectralNet#27]
Hi,
Thanks for the implementation. While I am looking into the code, I feel confused about some lines. For "pairs_per_pt = max(1, min(k, int(tot_pairs / (n * 2))))" in line 150 of pairs.py, what is the "pairs_per_pt" used for and what is the meaning of "tot_pairs / (n * 2)?

**Comment by AmitaiYacobi** [comment]
Highly recommend the use of our new PyTorch implementation which can now be installed and used as a pip package.
Link -  https://github.com/shaham-lab/SpectralNet
