### ISSUE TITLE
how to use new dataset?

### ISSUE THREAD

**Issue by pennywei** [KlugerLab/SpectralNet#7]
How can I implement SpectralNet on my own pictures for clustering?
don't know how to do pass a tuple to get_data containing four elements in the following order: (x_train, x_test, y_train, y_test).
how to pass and process  my own pictures?
Please give me some advice to solve it.Thanks

**Comment by lihenryhfl** [comment]
Take a look at the example code in the README. In particular, the lines:
```python
# load dataset
x_train, x_test, y_train, y_test = load_new_dataset_data()
new_dataset_data = (x_train, x_test, y_train, y_test)

# preprocess dataset
data = get_data(params, new_dataset_data)
```

where `load_new_dataset_data()` is your custom function that loads your new dataset.

**Comment by lihenryhfl** [comment]
Closing this for now. Please feel free open another issue or email me if you have any other questions!
