### ISSUE TITLE
Mistake in creating pairs from labeled data?

### ISSUE THREAD

**Issue by lanyiyun** [KlugerLab/SpectralNet#9]
Hi, I notice that in the following code, shouldn't the 2nd `create_paris_from_labeled_data` use `x_val_labeled` instead of `x_train_labeled`? And the 2nd `y_train_labeled` should be `y_val_labeled`?
 
Under `data.py`, the `get_data` method

```
#get pairs for labeled data

class_indices = [np.where(y_train_labeled == i)[0] for i in range(params['n_clusters'])]

pairs_train_labeled, dist_train_labeled = pairs.create_pairs_from_labeled_data(x_train_labeled, class_indices)

class_indices = [np.where(y_train_labeled == i)[0] for i in range(params['n_clusters'])]

pairs_val_labeled, dist_val_labeled = pairs.create_pairs_from_labeled_data(x_train_labeled, class_indices)
```

**Comment by lihenryhfl** [comment]
Hi lanyiyun, you're totally right! There's no supervised / semi-supervised training right now, so thankfully this doesn't affect anything, but it would be pretty bad when they are implemented. If you want, you can make the change, otherwise I'll fix it in a bit!

**Comment by lihenryhfl** [comment]
Fixed and closed
